### ISSUE TITLE
No functionality 

### ISSUE THREAD

**Issue by ChillHorse** [jakethekoenig/Fitbit-Coffee-Logger#1]
On a fitbit sense only three zeros are displayed. 
They appear centered and in an vertical row.
Tapping in the bottom right corner the watch slightly vibrates but beyond that there's no functionality

**Comment by jakethekoenig** [comment]
Sorry about that and thanks for bringing it to my attention. I'm not sure what might cause this problem.
 
Could you check the app settings (located in the phone) and try changing the color?

I'll try to reproduce this myself but unfortunately I'm running into a Fitbit bug which is preventing me from downloading any apps from the gallery at the moment.

**Comment by ChillHorse** [comment]
Indeed! Changing the color first does fix the displaying issue.

**Comment by jakethekoenig** [comment]
Awesome, glad that fixed it. I probably have a bad default set somewhere. As you can probably tell from the code this is not the most thoroughly tested app so I'm glad you brought this to my attention.

Mind if I ask: What was the color scheme before you changed it? Was the text orange, the background black and the buttons invisible?

**Comment by ChillHorse** [comment]
the default was orange Text, black background and invisible buttons
